### ISSUE TITLE
Page /adverts

### ISSUE THREAD

**Issue by exibit** [dubitoph/roadtrip#1]
Plusiuers soucis JS empêche des comportements de se mettre en place : navigation au scroll, select custom.

**Comment by dubitoph** [comment]
Pourrais-tu me donner des exemples d'erreurs js? Pour ma part, je n'en ai qu'une qui ne devrait avoir aucun impact (GET https://ipinfo.io/?callback=jQuery341018550755952476594_1570815096999&_=1570815097000 net::ERR_ABORTED 429), le reste étant des warnings liés à la future version de Chrome (warnings dont j'ai discuté avec Stripe).

**Comment by exibit** [comment]
<img width="579" alt="Capture d’écran 2019-10-11 à 22 30 51" src="https://user-images.githubusercontent.com/2632397/66683053-d24bf480-ec76-11e9-8efd-e7e4884302e5.png">

**Comment by dubitoph** [comment]
Ok, je viens de pouvoir reproduire l'erreur. Celle-ci ne survient que lorsqu'on fait appel au module de stylisation du select lorsqu'on tente de sélectionner une valeur dans un select.

La première erreur que j'ai eue est survenue lorsque j'ai sélectionné une valeur dans le select de la homepage :

![image](https://user-images.githubusercontent.com/47710530/66698809-779bb280-ece1-11e9-9824-f2c2d74d5a88.png)


 Il faudrait donc peut-être que tu vérifies ce qui cloche dans l'appel à ce module.

**Comment by exibit** [comment]
Oui c'est bizarre, je ne comprends pas pourquoi il fonctionne en homepage et pas sur cette page

**Comment by exibit** [comment]
Sur cette page il manque la class .select-hidden qui est sur la home alors qu'on fait appel au même module `{{ form_widget(form.minimumBedsNumber) }}`

**Comment by dubitoph** [comment]
Moi, j'ai bien une erreur en homepage lorsque je tente de sélectionner un choix dans le nombre de places... C'est l'erreur que j'ai référencée ci-dessus.

**Comment by exibit** [comment]
Salut Tof,
J'ai testé l'une ou l'autre chose avec le select. Selon moi le soucis vient principalement du fait qu'il y a des chaps vides dans les options : 
![Capture d’écran 2019-10-14 à 09 13 21](https://user-images.githubusercontent.com/2632397/66734319-ece2c100-ee62-11e9-97e0-c686f618c4ab.png)

Sur la homepage ca ne pose pas de problème car il y a un select sur les 4 places (je ne vois par contre pas où il est déclaré). Sur la page de résultats il n'y a pas de selected alors il ne sait pas créer de texte par défaut à afficher et le champ est "cassé" visuellement. J'ai actuellement résolu le problème en ajouter une class placeholder sur la déclaration du champ : https://symfony.com/doc/current/reference/forms/types/choice.html#placeholder

Pas sûr que ce soit la meilleure option, je pense qu'il faudrait appliquer un selected sur une valeur "all" par défaut que les gens peuvent ensuite changer.

J'ai également ajouter la class "select hidden" qui manquait aux 3 champs et le rendu est désormais correct.

**Comment by exibit** [comment]
Je n'ai plus d'erreur js du coup.

**Comment by exibit** [comment]
Il y a cette option qui a l'air intéressante aussi : https://symfony.com/doc/current/reference/forms/types/choice.html#empty-data

**Comment by dubitoph** [comment]
Erreurs js corrigées dans le module 'cusstom select' via l'ajout de la libraire jquery-ui
