### ISSUE TITLE
Homepage > prévoir un formulaire signup court

### ISSUE THREAD

**Issue by exibit** [dubitoph/roadtrip#2]
Avec uniquement :

1. email 
2. mot de passe 
3. retype du mot de passe

Il serait aussi bien utiliser dans le popup signup que dans la zone de la home d'invitation à s'inscrire.

**Comment by dubitoph** [comment]
Done. Attention cependant, il y a lieu d'exécuter le fichier de migration car il y a eu une modification du schéma de la base de données.

Etant donné que Symfony exige un nom d'utilisateur pour que son module Security fonctionne, je n'ai pas pu le supprimer.

Enfin, je me pose la question de l'opportunité de garder ce formulaire : à plusieurs endroits sur le site et dans les mails envoyés et reçu, j'utilise les nom et prénom de l'utilisateurs. Dès lors, si on laisse ce formulaire en place, il va falloir à chaque fois vérifier si ils ont été complétés, sinon, il faudra les remplacer par le nom d'utilisateur, ce que je trouve personnellement moins sympa.

Pour conclure, je trouve que pour un très petit gain pour l'utilisateur (uniquement le nom, le prénom et le numéro de téléphone facultatif en moins), l'impact sur le fonctionnement global est conséquent.
