### ISSUE TITLE
Création d'une rubrique FAQ

### ISSUE THREAD

**Issue by exibit** [dubitoph/roadtrip#5]
Question / réponse + catégories de questions.

**Comment by dubitoph** [comment]
FAQ réalisée. 
Accès à la gestion des rubriques via http://127.0.0.1:8000/backend/FAQ/category/index et accès à la gestion des questions/réponses via http://127.0.0.1:8000/backend/FAQ/question/index.
Accès à la liste des questions triées par rubrique accessible via http://127.0.0.1:8000/faq/index
