### ISSUE TITLE
Lorsque l'utilisateur est connecté, sur la homepage, dans la section "home-subscribe", afficher autre chose que le formulaire d'inscription 

### ISSUE THREAD

**Issue by dubitoph** [dubitoph/roadtrip#6]

**Comment by exibit** [comment]
Bonne question :-) Est-ce qu'on ne ferait pas disparaitre tout simplement toute la zone ?

**Comment by dubitoph** [comment]
Comme discuté, j'ai remplacé le formulaire par un lien vers le formulaire complet en modal si l'utilisateur n'est pas connecté, sinon vers son tableau de bord.
